title: "Beate Faust"
email: dr.bfaust@gmx.de
description: "Zahnartztpraxis Dr. Faust"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://faust-beate.de"
repository: "faust-beate/faust-beate.github.io"

# Build settings
future: true
markdown: kramdown
excerpt_separator: <!--more-->
exclude:
  - Gemfile
  - Gemfile.lock

# SASS settings
sass:
  sass_dir: assets/css
